"part: game client":
  - src/Components/Modules/Stats*

"part: game server":
  - src/Components/Modules/Dedicated*

"part: zonebuilder":
  - src/Components/Modules/ZoneBuilder*

"area: menus":
  - src/Components/Modules/Menus*

"area: anticheat":
  - src/Components/Modules/AntiCheat*

"area: serverlist":
  - src/Components/Modules/ServerList*

"area: weapons":
  - src/Components/Modules/Weapon*

"area: networking":
  - src/Components/Modules/Auth*
  - src/Components/Modules/Network*
  - src/Components/Modules/Node*
  - src/Components/Modules/PlayerName*
  - src/Components/Modules/RCon*
  - src/Components/Modules/Session*

"area: continuous integration":
  - "*appveyor*"
  - ".github/workflows/**"
  - Jenkinsfile

"status: work in progress":
  - "**"